<a href="https://colab.research.google.com/github/Meshi1520/Machine-Learning/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = sns.load_dataset("titanic")

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.drop(["deck","embark_town","alive","class","who","adult_male"],axis = 1,inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

In [ ]:
df.dropna(subset = ['embarked'],inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
columns = ['sex','embarked']
for i in columns:
  le = LabelEncoder()
  df[i] = le.fit_transform(df[i])

In [ ]:
df = df.astype(int)

In [ ]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [ ]:
X = df.drop("survived",axis = 1)
y = df["survived"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test , y_train, y_test = train_test_split(X,y,test_size = 0.40,random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0])

In [ ]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
177    0
599    1
441    0
164    0
249    0
Name: survived, Length: 356, dtype: int64

In [ ]:
#for classification problem we have confusion matrix

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [ ]:
accuracy_score(y_test,y_pred)

0.8061797752808989

In [ ]:
confusion_matrix(y_test,y_pred)

array([[182,  32],
       [ 37, 105]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       214
           1       0.77      0.74      0.75       142

    accuracy                           0.81       356
   macro avg       0.80      0.79      0.80       356
weighted avg       0.81      0.81      0.81       356

In [ ]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
177       1    0   50      0      0    28         0      1
599       1    1   49      1      0    56         0      0
441       3    1   20      0      0     9         2      1
164       3    1    1      4      1    39         2      0
249       2    1   54      1      0    26         2      0

[356 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = knn_model.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred)

0.8117977528089888

In [ ]:
confusion_matrix(y_test,y_pred)

array([[185,  29],
       [ 38, 104]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85       214
           1       0.78      0.73      0.76       142

    accuracy                           0.81       356
   macro avg       0.81      0.80      0.80       356
weighted avg       0.81      0.81      0.81       356

In [ ]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
177       1    0   50      0      0    28         0      1
599       1    1   49      1      0    56         0      0
441       3    1   20      0      0     9         2      1
164       3    1    1      4      1    39         2      0
249       2    1   54      1      0    26         2      0

[356 rows x 8 columns]

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB()
model_nb.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred_NB = model_nb.predict(X_test)

In [ ]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0])

In [ ]:
accuracy_score(y_test,y_pred_NB)

0.7780898876404494

In [ ]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.83      0.79      0.81       214
           1       0.71      0.76      0.73       142

    accuracy                           0.78       356
   macro avg       0.77      0.78      0.77       356
weighted avg       0.78      0.78      0.78       356

In [ ]:
confusion_matrix(y_test,y_pred_NB)

array([[169,  45],
       [ 34, 108]])

In [ ]:
#decision trees
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model_DT = DecisionTreeClassifier()
#ctrl + shift +space
model_DT.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_DT = model_DT.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_DT)

0.7893258426966292

In [ ]:
confusion_matrix(y_test,y_pred_DT)

array([[182,  32],
       [ 43,  99]])

In [ ]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.81      0.85      0.83       214
           1       0.76      0.70      0.73       142

    accuracy                           0.79       356
   macro avg       0.78      0.77      0.78       356
weighted avg       0.79      0.79      0.79       356

In [ ]:
from sklearn.svm import SVC
model_svm = SVC(kernel = 'linear')
#kernel = rbf
model_svm.fit(X_train_scaled,y_train)

SVC(kernel='linear')

In [ ]:
y_pred_svm = model.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_svm)

0.4044943820224719

In [ ]:
confusion_matrix(y_test,y_pred_svm)

array([[  2, 212],
       [  0, 142]])

In [ ]:
X_test_scaled

array([[ 0.79054795,  0.70511773, -0.11378209, ..., -0.48171599,
         0.58669668,  0.8254623 ],
       [-1.64507089, -1.41820289, -1.18988092, ...,  1.62145708,
         0.58669668, -1.21144236],
       [ 0.79054795, -1.41820289, -1.18988092, ..., -0.40726739,
        -1.94536268, -1.21144236],
       ...,
       [ 0.79054795,  0.70511773, -0.72869571, ..., -0.44449169,
         0.58669668,  0.8254623 ],
       [ 0.79054795,  0.70511773, -2.18911555, ...,  0.11387284,
         0.58669668, -1.21144236],
       [-0.42726147,  0.70511773,  1.88468716, ..., -0.12808512,
         0.58669668, -1.21144236]])

In [ ]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [ ]:
X = df.drop('survived',axis =1)

In [ ]:
y = df['survived']

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scaler = StandardScaler()

In [ ]:
X_scaled = scaler.fit_transform(X)

In [ ]:
X_scaled

array([[ 0.82520863,  0.73534203, -0.57802333, ..., -0.49673282,
         0.58683958, -1.22934919],
       [-1.57221121, -1.35991138,  0.65537059, ...,  0.79153916,
        -1.93955453, -1.22934919],
       [ 0.82520863, -1.35991138, -0.26967485, ..., -0.49673282,
         0.58683958,  0.81343853],
       ...,
       [ 0.82520863, -1.35991138, -0.03841349, ..., -0.17466483,
         0.58683958, -1.22934919],
       [-1.57221121,  0.73534203, -0.26967485, ..., -0.03376008,
        -1.93955453,  0.81343853],
       [ 0.82520863,  0.73534203,  0.19284787, ..., -0.49673282,
        -0.67635748,  0.81343853]])

In [ ]:
scores = cross_val_score(model_svm,X_scaled,y,cv = 5,scoring = 'accuracy')

In [ ]:
print(scores)

[0.80337079 0.80898876 0.78651685 0.75280899 0.78531073]

In [ ]:
print(scores.mean())

0.7873992255443407

In [ ]:
scores = cross_val_score(knn_model,X_scaled,y,cv = 5,scoring = 'accuracy')

In [ ]:
print(scores)

[0.78089888 0.76404494 0.8258427  0.81460674 0.8079096 ]

In [ ]:
#there is k folds cross validation and then we also have hyperparameter tuning